### PR TITLE
Refined block design and some semi-major fixes

### PR DESCRIPTION
**Pull request by HrabCOrp**
Added: demo design of basic blocks.
Added: page-wrapper to fix scrollbar.
Added: Open Sans font.
Added: some comments.

Changed: color scheme and block fonts.
Changed: image-block now has size of an image within it.

Fixed: scaling and scrolling (partially) on low content size.

Removed: bold-line border when editing block contents.
Removed: obsolete blocks.
Removed: script test.

### CODE REVIEW

**Review by rsviatoshchuk — APPROVED** [review]
Good commit description!

**Comment by KekemonBS** [comment]
Looks good, nice drop-down section.

**Review by KekemonBS — COMMENTED** [review]
Reviewed

**Review by KekemonBS — COMMENTED** [review]
fek

**Pull request merged**
